# Generated by Django 2.2.4 on 2019-08-27 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190826_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatarUrl',
            field=models.URLField(default='http://carryu.com', null=True, verbose_name='头像链接'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登陆时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickName',
            field=models.CharField(max_length=30, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.TextField(verbose_name='供admin登陆密码'),
        ),
    ]
